name: Build LaTeX Documentation

on:
  push:
    paths:
      - 'doc/'  # Define the path to your documentation directory

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive

      - name: Compile LaTeX
        run: |
          make
          chmod +x usermanual.pdf
        working-directory: doc/

      - name: Upload Documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: doc/usermanual.pdf

      - name: Commit and Push Changes
        run: |
          git config user.email "dashs@hawaii.edu"
          git config user.name "Soumyaranjan Dash"
          git add usermanual.pdf
          git commit -m "Add generated documentation PDF"
          git push
        working-directory: doc/


