name: Build LaTeX Documentation

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive

      - name: Compile LaTeX
        run: |
          cd doc/
          make

      - name: Upload Documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: usermanual.pdf

