name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up gfortran
        run: sudo apt-get update && sudo apt-get install gfortran

      - name: Install NetCDF
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libnetcdf-dev
          sudo apt-get install netcdf-bin
        env:
          NETCDF_DIR: /usr

      - name: Set up Miniconda
        run: |
          # Download and install Miniconda
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          conda init bash
          echo "Conda installed at $HOME/miniconda"
        env:
          NETCDF_DIR: /usr

      - name: Install NetCDF-Fortran
        run: |
          conda install -c conda-forge netcdf-fortran
          echo "NetCDF-Fortran installed via Conda"
        env:
          NETCDF_DIR: /usr

      - name: Set Library Paths
        run: |
          echo "/usr/lib/x86_64-linux-gnu" | sudo tee -a /etc/ld.so.conf.d/netcdf.conf
          sudo ldconfig
        env:
          NETCDF_DIR: /usr

      - name: Find the location of netcdf libraries.
        run: nc-config --all

      - name: Build
        run: make -f makefile.git # Use the appropriate build command, e.g., make or ./build.sh

      - name: Test
        run: ./bin/SFT1D initial_parameter.nml # Modify for your specific testing procedure

