name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up gfortran
        run: sudo apt-get update && sudo apt-get install gfortran

      - name: Set up netcdf
        run: |
             sudo apt-get update -qq
             sudo apt-get install -y libnetcdf-dev
             export NETCDF_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
             export NETCDF_INCLUDE_PATH=/usr/include
             echo "export NETCDF_INCLUDE_PATH=$NETCDF_INCLUDE_PATH" >> $GITHUB_ENV
        env:
             NETCDF_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu
             NETCDF_INCLUDE_PATH: /usr/include

      - name: Install locate command
        run: sudo apt-get install mlocate

      - name: Find the location of netcdf libraries.
        run: nc-config --all

      - name: Check if the mod file is present
        run: locate netcdf.mod

      - name: Build
        run: make -f makefile.git # Use the appropriate build command, e.g., make or ./build.sh

      - name: Test
        run: ./bin/SFT1D initial_parameter.nml # Modify for your specific testing procedure

