name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up gfortran
        run: sudo apt-get update && sudo apt-get install gfortran

      - name: Set up netcdf
        id: netcdf-check
        run: |
          if [ ! -f /usr/include/netcdf.mod ]; then
            echo "NetCDF not found, installing..."
            sudo apt-get update -qq
            sudo apt-get install -y libnetcdf-dev
          else
            echo "NetCDF is already installed."
          fi

      - name: Find the location of netcdf libraries.
        run: nf-config --all

      - name: Build
        run: make -f makefile.git # Use the appropriate build command, e.g., make or ./build.sh

      - name: Test
        run: ./bin/SFT1D initial_parameter.nml # Modify for your specific testing procedure

