name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up gfortran and gcc
        run: |
          sudo apt-get update > config.log 2>&1
          sudo apt-get install gfortran > config.log 2>&1
          sudo apt-get install -y gcc > config.log 2>&1
          sudo apt-get install -y openmpi-bin > config.log 2>&1

      - name: Download and Set up netCDF.
        run: |
          chmod +x install_netcdf.sh
          sudo CC=gcc FC=gfortran MAINDIR=/usr/local/netcdf ./install_netcdf.sh
        # Make the installation script executable and run it

      - name: Build
        run: make -f makefile.git # Use the appropriate build command, e.g., make

      - name: Test
        run: echo "Code is building fine."
