name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up gfortran and gcc
        run: sudo apt-get update && sudo apt-get install gfortran && sudo apt-get install -y gcc

      - name: Set the installation directory
        run: echo "INSTALL_DIR=${{ github.workspace }}/my_packages" >> $GITHUB_ENV

      - name: Download and Set up netCDF.
        run: |
          chmod +x install_netcdf.sh
          sudo CC=gcc FC=gfortran MAINDIR=$INSTALL_DIR ./install_netcdf.sh
        # Make the installation script executable and run it

      - name: Show Compilation Options
        run: |
          $INSTALL_DIR/netcdf/bin/nf-config --all

      - name: Build
        run: make -f makefile.git # Use the appropriate build command, e.g., make or ./build.sh

      - name: Test
        run: ./bin/SFT1D initial_parameter.nml # Modify for your specific testing procedure

